name: 构建并推送Sales Coach Docker镜像到阿里云

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置构建时间作为版本号
        id: build_time
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: 登录阿里云容器镜像服务
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: aliyun7428295517
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/heheer/sales-coach:latest
            registry.cn-hangzhou.aliyuncs.com/heheer/sales-coach:${{ steps.build_time.outputs.VERSION }}